# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 09:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Outst', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.CharField(max_length=250)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Outst.Info')),
            ],
        ),
    ]
