# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Outst', '0002_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved',
            name='info',
        ),
        migrations.DeleteModel(
            name='Approved',
        ),
    ]
