# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-29 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Outst', '0003_auto_20170129_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('accepted', models.CharField(max_length=250)),
            ],
        ),
    ]
